#version 450 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0, std430) buffer ScanDataBuffer {
    uint uScanData[];
};
layout(binding = 1, std430) readonly buffer ScanParentBuffer {
    uint uScanParent[];
};

layout(push_constant) uniform RhiPushConstants {
    // x: data word offset; y: parent word offset;
    // z: element count; w: elements per parent block.
    uvec4 uOffsetsCountAndBlockSize;
};

void main() {
    const uint index = gl_GlobalInvocationID.x;
    if (index >= uOffsetsCountAndBlockSize.z) {
        return;
    }
    const uint parentIndex = index / uOffsetsCountAndBlockSize.w;
    uScanData[uOffsetsCountAndBlockSize.x + index] +=
        uScanParent[uOffsetsCountAndBlockSize.y + parentIndex];
}
