#ifndef MECRAFT_STATIC_MESH_RAY_TRACING_CONTRACT_GLSL
#define MECRAFT_STATIC_MESH_RAY_TRACING_CONTRACT_GLSL

const uint STATIC_MESH_RAY_TRACING_CONTRACT_VERSION = 1u;
const uint STATIC_MESH_RAY_TRACING_GEOMETRY_REVISION = 1u;
const uint STATIC_MESH_RAY_TRACING_VERTEX_STRIDE = 48u;
const uint STATIC_MESH_RAY_TRACING_POSITION_OFFSET = 0u;
const uint STATIC_MESH_RAY_TRACING_NORMAL_OFFSET = 12u;
const uint STATIC_MESH_RAY_TRACING_TANGENT_OFFSET = 24u;
const uint STATIC_MESH_RAY_TRACING_UV_OFFSET = 40u;

struct StaticMeshPrimitiveMetadata {
    uint materialIndex;
    uint stableMaterialId;
    uint stableGeometryId;
    uint contractVersion;
};

#endif // MECRAFT_STATIC_MESH_RAY_TRACING_CONTRACT_GLSL
