if(NOT DEFINED MECRAFT_SOURCE_DIR)
    message(FATAL_ERROR "MECRAFT_SOURCE_DIR is required")
endif()

file(GLOB_RECURSE PRODUCT_FILES LIST_DIRECTORIES false
    "${MECRAFT_SOURCE_DIR}/src/*"
    "${MECRAFT_SOURCE_DIR}/assets/shaders/*"
    "${MECRAFT_SOURCE_DIR}/assets/config/*")
list(APPEND PRODUCT_FILES "${MECRAFT_SOURCE_DIR}/CMakeLists.txt")

set(REMOVED_FEATURE_REFERENCES "")
foreach(PRODUCT_FILE IN LISTS PRODUCT_FILES)
    file(READ "${PRODUCT_FILE}" PRODUCT_CONTENT)
    string(TOLOWER "${PRODUCT_CONTENT}" PRODUCT_CONTENT_LOWER)
    if(PRODUCT_CONTENT_LOWER MATCHES "voxel[ _-]*gi")
        list(APPEND REMOVED_FEATURE_REFERENCES "${PRODUCT_FILE}")
    endif()
endforeach()

if(REMOVED_FEATURE_REFERENCES)
    list(JOIN REMOVED_FEATURE_REFERENCES "\n" REFERENCE_REPORT)
    message(FATAL_ERROR "Removed Voxel GI references found:\n${REFERENCE_REPORT}")
endif()
